//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace SilverNiti.Core.ContentModels
{
	// Mixin content Type 1126 with alias "silverNitiSEO"
	/// <summary>SilverNiti.SEO</summary>
	public partial interface ISilverNitiSeo : IPublishedContent
	{
		/// <summary>Description</summary>
		string Description { get; }

		/// <summary>Keywords</summary>
		string Keywords { get; }

		/// <summary>MetaTitle</summary>
		string MetaTitle { get; }
	}

	/// <summary>SilverNiti.SEO</summary>
	[PublishedContentModel("silverNitiSEO")]
	public partial class SilverNitiSeo : PublishedContentModel, ISilverNitiSeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "silverNitiSEO";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SilverNitiSeo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SilverNitiSeo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return GetDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetDescription(ISilverNitiSeo that) { return that.GetPropertyValue<string>("description"); }

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("keywords")]
		public string Keywords
		{
			get { return GetKeywords(this); }
		}

		/// <summary>Static getter for Keywords</summary>
		public static string GetKeywords(ISilverNitiSeo that) { return that.GetPropertyValue<string>("keywords"); }

		///<summary>
		/// MetaTitle
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return GetMetaTitle(this); }
		}

		/// <summary>Static getter for MetaTitle</summary>
		public static string GetMetaTitle(ISilverNitiSeo that) { return that.GetPropertyValue<string>("metaTitle"); }
	}
}
