//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace SilverNiti.Core.ContentModels
{
	/// <summary>SilverNiti.HomePage</summary>
	[PublishedContentModel("silverNitiHomePage")]
	public partial class SilverNitiHomePage : PublishedContentModel, ISilverNitiBase, ISilverNitiNavigation, ISilverNitiSeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "silverNitiHomePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SilverNitiHomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SilverNitiHomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}

		///<summary>
		/// Main Menu
		///</summary>
		[ImplementPropertyType("mainMenu")]
		public Archetype.Models.ArchetypeModel MainMenu
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("mainMenu"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return SilverNitiBase.GetTitle(this); }
		}

		///<summary>
		/// Hide From Navigation
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return SilverNitiNavigation.GetHideFromNavigation(this); }
		}

		///<summary>
		/// Hide in Sitemap
		///</summary>
		[ImplementPropertyType("hideInSitemap")]
		public bool HideInSitemap
		{
			get { return SilverNitiNavigation.GetHideInSitemap(this); }
		}

		///<summary>
		/// Navigation Title
		///</summary>
		[ImplementPropertyType("navigationTitle")]
		public string NavigationTitle
		{
			get { return SilverNitiNavigation.GetNavigationTitle(this); }
		}

		///<summary>
		/// Show Childs in Navigation
		///</summary>
		[ImplementPropertyType("showChildsInNavigation")]
		public bool ShowChildsInNavigation
		{
			get { return SilverNitiNavigation.GetShowChildsInNavigation(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return SilverNitiSeo.GetDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("keywords")]
		public string Keywords
		{
			get { return SilverNitiSeo.GetKeywords(this); }
		}

		///<summary>
		/// MetaTitle
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return SilverNitiSeo.GetMetaTitle(this); }
		}
	}
}
