//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "d453c40f5b45712c")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1081 with alias "silverNitiBase"
	/// <summary>SilverNiti.Base</summary>
	public partial interface ISilverNitiBase : IPublishedContent
	{
		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>SilverNiti.Base</summary>
	[PublishedContentModel("silverNitiBase")]
	public partial class SilverNitiBase : PublishedContentModel, ISilverNitiBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "silverNitiBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SilverNitiBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SilverNitiBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(ISilverNitiBase that) { return that.GetPropertyValue<string>("title"); }
	}

	/// <summary>SilverNiti.ContentPage</summary>
	[PublishedContentModel("contentPage")]
	public partial class ContentPage : PublishedContentModel, ISilverNitiBase, ISilverNitiNavigation, ISilverNitiSeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiBase.GetTitle(this); }
		}

		///<summary>
		/// Hide From Navigation
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiNavigation.GetHideFromNavigation(this); }
		}

		///<summary>
		/// Hide in Sitemap
		///</summary>
		[ImplementPropertyType("hideInSitemap")]
		public bool HideInSitemap
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiNavigation.GetHideInSitemap(this); }
		}

		///<summary>
		/// Navigation Title
		///</summary>
		[ImplementPropertyType("navigationTitle")]
		public string NavigationTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiNavigation.GetNavigationTitle(this); }
		}

		///<summary>
		/// Show Childs in Navigation
		///</summary>
		[ImplementPropertyType("showChildsInNavigation")]
		public bool ShowChildsInNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiNavigation.GetShowChildsInNavigation(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiSeo.GetDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("keywords")]
		public string Keywords
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiSeo.GetKeywords(this); }
		}

		///<summary>
		/// MetaTitle
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiSeo.GetMetaTitle(this); }
		}
	}

	/// <summary>SilverNiti.HomePage</summary>
	[PublishedContentModel("silverNitiHomePage")]
	public partial class SilverNitiHomePage : PublishedContentModel, ISilverNitiBase, ISilverNitiNavigation, ISilverNitiSeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "silverNitiHomePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SilverNitiHomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SilverNitiHomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}

		///<summary>
		/// Main Menu
		///</summary>
		[ImplementPropertyType("mainMenu")]
		public Archetype.Models.ArchetypeModel MainMenu
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("mainMenu"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiBase.GetTitle(this); }
		}

		///<summary>
		/// Hide From Navigation
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiNavigation.GetHideFromNavigation(this); }
		}

		///<summary>
		/// Hide in Sitemap
		///</summary>
		[ImplementPropertyType("hideInSitemap")]
		public bool HideInSitemap
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiNavigation.GetHideInSitemap(this); }
		}

		///<summary>
		/// Navigation Title
		///</summary>
		[ImplementPropertyType("navigationTitle")]
		public string NavigationTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiNavigation.GetNavigationTitle(this); }
		}

		///<summary>
		/// Show Childs in Navigation
		///</summary>
		[ImplementPropertyType("showChildsInNavigation")]
		public bool ShowChildsInNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiNavigation.GetShowChildsInNavigation(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiSeo.GetDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("keywords")]
		public string Keywords
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiSeo.GetKeywords(this); }
		}

		///<summary>
		/// MetaTitle
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SilverNitiSeo.GetMetaTitle(this); }
		}
	}

	// Mixin content Type 1084 with alias "silverNitiNavigation"
	/// <summary>SilverNiti.Navigation</summary>
	public partial interface ISilverNitiNavigation : IPublishedContent
	{
		/// <summary>Hide From Navigation</summary>
		bool HideFromNavigation { get; }

		/// <summary>Hide in Sitemap</summary>
		bool HideInSitemap { get; }

		/// <summary>Navigation Title</summary>
		string NavigationTitle { get; }

		/// <summary>Show Childs in Navigation</summary>
		bool ShowChildsInNavigation { get; }
	}

	/// <summary>SilverNiti.Navigation</summary>
	[PublishedContentModel("silverNitiNavigation")]
	public partial class SilverNitiNavigation : PublishedContentModel, ISilverNitiNavigation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "silverNitiNavigation";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SilverNitiNavigation(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SilverNitiNavigation, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hide From Navigation
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return GetHideFromNavigation(this); }
		}

		/// <summary>Static getter for Hide From Navigation</summary>
		public static bool GetHideFromNavigation(ISilverNitiNavigation that) { return that.GetPropertyValue<bool>("hideFromNavigation"); }

		///<summary>
		/// Hide in Sitemap
		///</summary>
		[ImplementPropertyType("hideInSitemap")]
		public bool HideInSitemap
		{
			get { return GetHideInSitemap(this); }
		}

		/// <summary>Static getter for Hide in Sitemap</summary>
		public static bool GetHideInSitemap(ISilverNitiNavigation that) { return that.GetPropertyValue<bool>("hideInSitemap"); }

		///<summary>
		/// Navigation Title
		///</summary>
		[ImplementPropertyType("navigationTitle")]
		public string NavigationTitle
		{
			get { return GetNavigationTitle(this); }
		}

		/// <summary>Static getter for Navigation Title</summary>
		public static string GetNavigationTitle(ISilverNitiNavigation that) { return that.GetPropertyValue<string>("navigationTitle"); }

		///<summary>
		/// Show Childs in Navigation
		///</summary>
		[ImplementPropertyType("showChildsInNavigation")]
		public bool ShowChildsInNavigation
		{
			get { return GetShowChildsInNavigation(this); }
		}

		/// <summary>Static getter for Show Childs in Navigation</summary>
		public static bool GetShowChildsInNavigation(ISilverNitiNavigation that) { return that.GetPropertyValue<bool>("showChildsInNavigation"); }
	}

	// Mixin content Type 1085 with alias "silverNitiSEO"
	/// <summary>SilverNiti.SEO</summary>
	public partial interface ISilverNitiSeo : IPublishedContent
	{
		/// <summary>Description</summary>
		string Description { get; }

		/// <summary>Keywords</summary>
		string Keywords { get; }

		/// <summary>MetaTitle</summary>
		string MetaTitle { get; }
	}

	/// <summary>SilverNiti.SEO</summary>
	[PublishedContentModel("silverNitiSEO")]
	public partial class SilverNitiSeo : PublishedContentModel, ISilverNitiSeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "silverNitiSEO";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SilverNitiSeo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SilverNitiSeo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return GetDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetDescription(ISilverNitiSeo that) { return that.GetPropertyValue<string>("description"); }

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("keywords")]
		public string Keywords
		{
			get { return GetKeywords(this); }
		}

		/// <summary>Static getter for Keywords</summary>
		public static string GetKeywords(ISilverNitiSeo that) { return that.GetPropertyValue<string>("keywords"); }

		///<summary>
		/// MetaTitle
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return GetMetaTitle(this); }
		}

		/// <summary>Static getter for MetaTitle</summary>
		public static string GetMetaTitle(ISilverNitiSeo that) { return that.GetPropertyValue<string>("metaTitle"); }
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
